---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  environments_path: './environments/'
  roles_path: './roles/'

platforms:
  - name: centos7
    driver:
      box: "matyunin/centos7"
      network:
      - ["private_network", {ip: "192.168.33.13"}]
      customize:
        memory: 2024
        natdnshostresolver1: "on"
        natdnsproxy1: "on"

suites:
  - name: default
    #provisioner:
  #    solo_rb:
  #     environment: development
        #environment: production
    run_list:
      - recipe[systemd::default]
    data_bags_path: "./data_bags" 
    #attributes: 

