---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  environments_path: './environments/'
  roles_path: './roles/'

platforms:
  - name: centos-7.1
    driver:
      box: "opscode_centos-7.1"
      box_url: "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box"
      network:
        #- ["private_network", {type: "dhcp"}]
        #- ["public_network",  bridge: 'en1: Thunderbolt 1']
      - ["private_network", {ip: "192.168.33.9"}]
      customize:
        memory: 2024
        natdnshostresolver1: "on"
        natdnsproxy1: "on"

  - name: ubuntu-14.04
    driver:
      box: "opscode-ubuntu-14.04"
      #box_url: "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box"
      network:
        #- ["private_network", {type: "dhcp"}]
        #- ["public_network",  bridge: 'en1: Thunderbolt 1']
      - ["private_network", {ip: "192.168.33.10"}]
      customize:
        memory: 2024
        natdnshostresolver1: "on"
        natdnsproxy1: "on"

suites:
  - name: default
    #provisioner:
  #    solo_rb:
  #     environment: development
        #environment: production
    run_list:
      - recipe[systemd::default]
    data_bags_path: "./data_bags" 
    #attributes: 

