Vagrant.configure("2") do |c|
  c.vm.box = "matyunin/centos7"
  c.vm.box_url = "http://spacewalk.asv.local/pub/vagrant/as-vbox-centos7.box"
  c.vm.hostname = "default-centos7.vagrantup.com"
  c.vm.network(:private_network, {:ip=>"192.168.33.13"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "2024"]
    p.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    p.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
end
